name: aud_cli_gc
description: Audanika Developer Command Line - Generate Code With Ease, e.g. Classes
version: 1.0.0
repository: https://github.com/inlavigo/aud_cli_gc

environment:
  sdk: ^3.4.0-120.0.dev

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  path: ^1.6.4
  super_string: ^1.0.3
  dart_style: ^2.3.4
  recase: ^4.1.0

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  pana: ^0.22.0
  test: ^1.24.0
  yaml: ^3.1.2
